### ISSUE TITLE
Synthetic methods in generic classes fails registration of mbeans

### ISSUE THREAD

**Issue by weissreto** [axonivy/ivymx#7]
In some situations where a mBean class extends a sub class with generic type parameters the java compiler redeclares methods defined on the sub class on the mBean class once again. This leads to problems when trying to register an mBean because of duplicated operators. The methods that are generated by the java compiler and therefore are not explicit declared in source code should be ignored.

**Comment by alexsuter** [comment]
Lukas and I have started in some github repos a dedicated CHANGELOG.md (https://keepachangelog.com/de/1.0.0/)
if you like it, you may can add here also a CHANGELOG.md
